fdm_a.o: fdm_a.c config.h fdm.h
fdm_d.o: fdm_d.c config.h fdm.h
fdm_f.o: fdm_f.c config.h fdm.h
fdm_h.o: fdm_h.c config.h fdm.h
fdm_s.o: fdm_s.c config.h fdm.h
fdm_v.o: fdm_v.c config.h fdm.h
gnu_regex.o: gnu_regex.c config.h gnu_regex.h
stress.o: stress.c fdm.h
